### ISSUE TITLE
Response payload 'Cart'

### ISSUE THREAD

**Issue by TakoFat** [t7yang/dummy-api#4]
在readme.md裡面，cart/my跟cart/:id都會回傳 "Cart"

但是用cart/my拿到的response，裡面的products是物品詳細內容
![image](https://github.com/t7yang/dummy-api/assets/136698603/65f83fb1-518c-4b1a-8f25-6e18f2d45a69)

而cart/:id拿到的products，僅是一個 number[]
![image](https://github.com/t7yang/dummy-api/assets/136698603/3893c968-809e-4de4-ae52-452e785f226d)

**Comment by t7yang** [comment]
done
